Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -4,13 +4,13 @@ on:
     push:
       branches: 
         - main
-      paths: 
-        - terraform/**
-    pull_request:
-      branches: 
-        - main
-      paths: 
-        - terraform/**
+    #   paths: 
+    #     - terraform/**
+    # pull_request:
+    #   branches: 
+    #     - main
+    #   paths: 
+    #     - terraform/**
 env:
     # credentials for deployment to AWS
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -43,23 +43,23 @@ jobs:
           run: terraform fmt -check
           continue-on-error: true 
 
-        - name: Terraform Validate
-          id: validate
-          run: terraform validate
+        # - name: Terraform Validate
+        #   id: validate
+        #   run: terraform validate
 
-        - name: Terraform Plan
-          id: plan
-          run: terraform plan -no-color -input=false -out planfile
-          continue-on-error: true 
+        # - name: Terraform Plan
+        #   id: plan
+        #   run: terraform plan -no-color -input=false -out planfile
+        #   continue-on-error: true 
 
-        - name: Terraform Plan Status 
-          if: steps.plan.outcome == 'failure'
-          run: exit 1
+        # - name: Terraform Plan Status 
+        #   if: steps.plan.outcome == 'failure'
+        #   run: exit 1
 
         - name: Terraform Apply
           id: destroy
           if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-          run: terraform destroy -auto-approve -input=false -parallelism=1 planfile
+          run: terraform destroy -auto-approve 
 
 
 
